name: 錯誤報告（繁體中文）
description: 提交 更好的基岩版中文體驗 錯誤報告
title: "[Bug] "
labels: ["Bug", "Pending"]
body:
  - type: markdown
    attributes:
      value: |
        提交報告前請注意：  
        1. 此處僅接受此資源包本身的錯誤報告。  
        2. 如有發現翻譯錯誤，或是您有更佳品質的翻譯，請至 [Crowdin](https://crowdin.com/project/better-zhtwhk-translation) 上提交您的翻譯。  
        3. 如有發現到沒有字串被翻譯的問題，請至 Crowdin 提交您的翻譯，或是按 [這裡](https://docs.google.com/forms/d/e/1FAIpQLSdX-quuE6q4jbDxLRgwGOLsEbwNNkQ3642yhLAMGW7HnDnXlg/viewform) 前往填寫表單。  
        
        感謝您抽出寶貴時間填寫此錯誤報告！  
  - type: textarea
    id: what-happened
    attributes:
      label: 錯誤描述
      description: 請詳細描述發生的錯誤資訊。
      placeholder: 告訴我們發生了什麼錯誤。
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 重現步驟
      description: 請描述觸發錯誤的步驟。
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: bash
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: 預期行為
      description: 請簡要描述您想要的效果。
    validations:
      required: true
  - type: input
    id: actual-behavior
    attributes:
      label: 實際行為
      description: 請簡要說明實際結果。
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: 更好的基岩版中文體驗 版本
      description: 你目前使用的是什麼版本的 更好的基岩版中文體驗？（例如 1.7.0，可從資源包標題中指示的版本號中找到。如果您使用的版本未在此處列出，則您使用的版本已過期。請更新到最新版本並嘗試再次重現該錯誤。）
      options:
        - 1.7.0
    validations:
      required: true
  - type: input
    id: game-version
    attributes:
      label: 你玩的是什麼遊戲版本？
      description: 請輸入受影響的遊戲版本。
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: 您正在使用的裝置的系統是什麼？
      options:
        - Windows
        - iOS
        - Android
        - 其他
    validations:
      required: false
