name: Merge pull requests

on:
  pull_request:
    branches:
      - l10n_main3
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge pull request
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff l10n_main3
          git push origin main
