name: UpdateLang

on: 
  schedule:
    - cron: "0 0 * * 1,2,3,4,5"
  workflow_dispatch:
  pull_request:
    branches:
      - l10n_main3
    types: [opened, synchronize]
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge Pull Request
        uses: actions/merge@v2
        with:
          branch: main
    
