name: Merge pull request

on:
  pull_request:
    branches:
      - l10n_main3

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/merge-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automatic merge"
