name: Auto Merge

on:
  pull_request:
    branches:
      - l10n_main3

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      # Check if the pull request is approved and all checks have passed
      - name: Check if merge conditions are met
        if: github.event.pull_request.approved && github.event.pull_request.mergeable && github.event.pull_request.status == "success"
        run: exit 0
      - name: Merge pull request
        run: |
          set -ex
          git fetch origin +refs/pull/*/head:refs/remotes/origin/pr/*
          git config --global user.email "yutayamamoto212@gmail.com"
          git config --global user.name "YutaYamamoto212"
          git checkout l10n_main3
          git merge origin/pr/${{ github.event.pull_request.number }} --ff-only --no-edit
          git push origin l10n_main3
